apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm-hellomct
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Truong-Giangg/Helm-Multi-SVCs.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hellomct
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true      # remove resources not in Git
      selfHeal: true   # fix drift automatically