apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullnameOverride }}-config
  namespace: {{ .Release.Namespace }}
data:
  appsettings.json: |
{{ .Files.Get (printf "configs/%s-appsettings.json" .Values.fullnameOverride) | indent 4 }}
